apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-website
  namespace: default
data:
  index.html: |
    <html>
      <body style="background-color: #f4f4f9; text-align: center; font-family: sans-serif; padding: 50px;">
        <h1>Olá, GitOps! 🐙</h1>
        <p>Meu ConfigMap foi injetado com sucesso pelo ArgoCD.</p>
      </body>
    </html>
