apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-website
  namespace: production # <-- Atualizado
data:
  index.html: |
    <html>
      <body style="background-color: #0d1117; color: #58a6ff; text-align: center; font-family: monospace; padding: 50px;">
        <h1>🚀 Ambiente de Produção Ativo!</h1>
        <p>Namespace: production | Gerenciado 100% via GitOps</p>
      </body>
    </html>