apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-nginx
  template:
    metadata:
      labels:
        app: meu-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        env: # <--- ADICIONAMOS ISSO AQUI
        - name: MINHA_CHAVE_API # O nome da variável dentro do Linux do container
          valueFrom:
            secretKeyRef:
              name: api-key-secret # O nome do Secret que criamos no Passo 1
              key: CHAVE_API # A chave exata dentro do Secret
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-website