apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: production # <-- Atualizado
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-nginx
  template:
    metadata:
      labels:
        app: meu-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        env: # <-- Lendo o Secret que criamos no Passo 2
        - name: MINHA_CHAVE_API
          valueFrom:
            secretKeyRef:
              name: api-key-secret
              key: CHAVE_API
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: nginx-website